# Generated by Django 4.1.5 on 2023-01-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmsSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cms_img', models.ImageField(upload_to='slider_img/')),
                ('cms_title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('cms_text', models.CharField(max_length=128, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайдер',
            },
        ),
    ]
