# Generated by Django 4.1.5 on 2023-01-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsslider',
            name='cms_cssstyle',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='CSS'),
        ),
        migrations.AlterField(
            model_name='cmsslider',
            name='cms_img',
            field=models.ImageField(upload_to='media/slider_img/'),
        ),
    ]
