# Generated by Django 4.1.5 on 2023-01-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_cmsslider_cms_cssstyle_alter_cmsslider_cms_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsslider',
            name='cms_cssstyle',
            field=models.CharField(default='-', max_length=256, null=True, verbose_name='CSS'),
        ),
    ]
