# Generated by Django 4.1.5 on 2023-01-16 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_commentcrm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentcrm',
            name='comment_bind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.order', verbose_name='Комментарий'),
        ),
    ]
